CREATE TABLE `user` (
	`id` INT(100) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(255) NULL DEFAULT NULL,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`userType` INT(10) NULL DEFAULT NULL,
	`accountStatus` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id` (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=57
;
